### ISSUE TITLE
Datalabels on Highmaps appearing bottom to top

### ISSUE THREAD

**Issue by LuongNV1** [justpy-org/justpy#452] opened 2022-08-24 09:58 UTC
I am facing a strange problem with Highmaps. I have a geojson map that Highmaps shows properly. Mouseover works and tooltips appear in the correct places. However, when I turn on data labels, they appear upside down. That is, a label that should appear near the bottom of the map
![image](https://user-images.githubusercontent.com/93819584/186389933-4dbe5d11-3a58-4122-9a72-9744338e90b4.png)

**Comment by WolfgangFahl** [comment] 2022-08-24 14:14
@LuongNV1 thank you for reporting this. This might be a duplicate of #315 which also seems depending on the version. Could you please provide the full python source code for your example. It would also be goo if you try out a pure java version of what you want to achieve in comparison to show what the difference between the justpy behavior and the native highcharts behavior is.

**Comment by WolfgangFahl** [comment] 2023-09-20 12:23
see #685

**Closed by WolfgangFahl** 2023-09-20 12:23 UTC
Labels: duplicate, wontfix, HighCharts
