### ISSUE TITLE
aggrid infinite recursion

### ISSUE THREAD

**Issue by theeveventh** [justpy-org/justpy#369] opened 2022-04-25 20:27 UTC
template/js/aggrid.js line 35: 
```
this.evaluate_formatters(grid_def); 
```
The above line causes an infinite recursion with tutorial example (https://justpy.io/grids_tutorial/database/).  For example, change the table selection from "albums" to "artist". 

(justpy version 0.2.3)

**Comment by elimintz** [comment] 2022-04-26 04:07
Thank you for flagging this

**Comment by WolfgangFahl** [comment] 2022-09-14 20:32
duplicate of #467

**Closed by WolfgangFahl** 2022-09-14 20:32 UTC
Labels: bug, AG Grid
